version: '3.9'
services:
  frontend:
    build: ./web-metrics-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./web-metrics-frontend/app:/app/app
      - ./web-metrics-frontend/public:/app/public
      - ./web-metrics-frontend/cypress:/app/cypress
    restart: always
    environment:
      - CHOKIDAR_USEPOLLING=true

  chrome:
    image: selenium/node-chrome:4.13.0-20231004
    shm_size: 2gb
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    deploy:
      replicas: 1
    entrypoint: bash -c 'SE_OPTS="--host $$HOSTNAME" /opt/bin/entry_point.sh'

  selenium-hub:
    image: selenium/hub:4.13.0-20231004
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/usr/src/app
