version: '3.9'
services:
  # frontend:
  #   build: ./web-metrics-frontend
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./frontend/src:/app/src
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    privileged: true